### ISSUE TITLE
FR: pilihan "kategori" di Laporan Penjual

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#13]
Mohon agar ada opsi "Kategori" di Laporan Penjualan.

Seperti di laporan Top Rank.

Sehingga laporan bisa ditampilkan hanya dari kategori tsb.

Default opsi kategori : SEMUA

Terimakasih.

**Comment by AbuMuhammad** [comment]
Berarti tambah laporan penjualan perbarang ya pak?

**Comment by sufehmi** [comment]
Tidak usah pak, cukup laporan yang ada, hanya ditambah opsi untuk memilih Kategori.

Thanks.

**Comment by sufehmi** [comment]
Ditambahkan opsi untuk memilih Kategori, diantara "Sampai" dan "Profil"

![screenshot from 2016-09-21 15-52-39](https://cloud.githubusercontent.com/assets/170206/18704271/804be28a-8013-11e6-9345-7314f015d934.png)

**Comment by AbuMuhammad** [comment]
Saat ini tampilannya per nota pak. Jadi kalau pakai kategori barang,
sepertinya tidak nyambung, karena nominalnya (perbaris) adalah nominal per
nota.
Kalau totalnya saja masih nyambung, tapi detailnya jadi tidak relevan,
kalau ada kategorinya

**Comment by AbuMuhammad** [comment]
Sudah ditambahkan pak
[ceb34c0](https://github.com/AbuMuhammad/ap3/commit/ceb34c0dee23ff79da3e93f15d702e9ff24531a0)

**Comment by AbuMuhammad** [comment]
![screenshot-report-penjualan-addkategori-med](https://cloud.githubusercontent.com/assets/3438768/18736912/01773aba-80b6-11e6-9d3c-8867e605feef.png)

![screenshot-report-penjualan-addkategori-l](https://cloud.githubusercontent.com/assets/3438768/18736914/08bb6a12-80b6-11e6-9593-87d8001e4640.png)

**Comment by sufehmi** [comment]
> Saat ini tampilannya per nota pak. Jadi kalau pakai kategori barang,
> sepertinya tidak nyambung, karena nominalnya (perbaris) adalah nominal per
> nota.

Wah iya, betul pak.......... maaf saya baru sadar ada reply ini

Anyway kalau sudah oke solusinya ini, silakan tolong langsung update pak ke toko ybs.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Sudah ditambahkan pak :senyum
Jadi nominal yg muncul adalah nominal barang2 yang berkategori terpilih
saja. Bukan nominal notanya. Tapi tampilannya tetap pernota

On 23 Sep 2016 15:44, "Harry Sufehmi" <notifications@github.com> wrote:

Saat ini tampilannya per nota pak. Jadi kalau pakai kategori barang,
sepertinya tidak nyambung, karena nominalnya (perbaris) adalah nominal per
nota.

Wah iya, betul pak.......... maaf saya baru sadar ada reply ini

Anyway kalau sudah oke solusinya ini, silakan tolong langsung update pak ke
toko ybs.

Terimakasih.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/AbuMuhammad/ap3/issues/13#issuecomment-249136459>, or mute
the thread
